env:
  commonjs: true
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2022
rules: {
  "no-console": 'off',
  "semi": 1,
  "quotes": ['error', 'single'],
  "no-trailing-spaces": [2, { 'skipBlankLines': true }],
  "no-use-before-define": [ 'error', { 'functions': false, 'variables': true } ],
  "prefer-destructuring": ["error", {"object": true, "array": false}]
}
